"""add Adventure and Character

Revision ID: ffe0fdd10a91
Revises: 896608ac1173
Create Date: 2023-03-15 20:12:19.604312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffe0fdd10a91"
down_revision = "896608ac1173"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adventures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("campaign", "one_shot", "two_shot", name="adventuretypeenum"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_adventures_created_at"), "adventures", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_adventures_id"), "adventures", ["id"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_characters_created_at"), "characters", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_table(
        "adventure_players",
        sa.Column("adventure_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("player", "dm", name="adventureroleenum"), nullable=False
        ),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["adventure_id"],
            ["adventures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("adventure_id", "player_id"),
    )
    op.create_index(
        op.f("ix_adventure_players_created_at"),
        "adventure_players",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_adventure_players_created_at"), table_name="adventure_players"
    )
    op.drop_table("adventure_players")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_created_at"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_adventures_id"), table_name="adventures")
    op.drop_index(op.f("ix_adventures_created_at"), table_name="adventures")
    op.drop_table("adventures")
    op.execute("DROP TYPE IF EXISTS adventuretypeenum;")
    op.execute("DROP TYPE IF EXISTS adventureroleenum;")
    # ### end Alembic commands ###
